const BEAUTY = [
  {
    name: "Makeup",
    list: [
      "Lipstick",
      "Lip Gloss",
      "Lip Liner",
      "Mascara",
      "Eyeliner",
      "Kajal",
      "Eyeshadow",
      "Foundation",
      "Primer",
      "Concealer",
      "Compact",
      "Nail Polish",
    ],
  },
  {
    name: "Skincare, Bath & Body",
    list: [
      "Face Moisturiser",
      "Cleanser",
      "Masks & Peel",
      "Sunscreen",
      "Serum",
      "Face Wash",
      "Eye Cream",
      "Lip Balm",
      "Body Lotion",
      "Body Wash",
      "Body Scrub",
      "Hand Cream",
    ],
  },
  {
    name: "Haircare",
    list: [
      "Shampoo",
      "Conditioner",
      "Hair Cream",
      "Hair Oil",
      "Hair Gel",
      "Hair Color",
      "Hair Serum",
      "Hair Accessory",
    ],
  },
  { name: "Fragrances", list: ["Perfume", "Deodorant", "Body Mist"] },
  { name: "Appliances", list: ["Hair Straightener", "Hair Dryer", "Epilator"] },
  { name: "Men's Grooming", list: ["Trimmers", "Beard Oil", "Hair Wax"] },
  { name: "Beauty Gift & Makeup Set", list: ["Beauty Gift", "Makeup Kit"] },
  {
    name: "Top Brands",
    list: [
      "Lakme",
      "Maybelline",
      "LOreal",
      "Philips",
      "Bath & Body Works",
      "THE BODY SHOP",
      "Biotique",
      "Mamaearth",
      "MCaffeine",
      "Nivea",
      "Lotus Herbals",
      "LOreal Professionnel",
      "KAMA AYURVEDA",
      "M.A.C",
      "Forest Essentials",
    ],
  },
];
export default BEAUTY;
export const KIDS = [
  {
    name: "Boys_Clothing",
    list: [
      "T-Shirts",
      "Shirts",
      "Shorts",
      "Jeans",
      "Trousers",
      "Clothing Sets",
      "Ethnic Wear",
      "Track Pants & Pyjamas",
      "Jacket, Sweater & Sweatshirts",
      "Party Wear",
      "Innerwear & Thermals",
      "Nightwear & Loungewear",
      "Value Packs",
    ],
  },
  {
    name: "Girls_Clothing",
    list: [
      "Dresses",
      "Tops",
      "Tshirts",
      "Clothing Sets",
      "Lehenga choli",
      "Kurta Sets",
      "Party wear",
      "Dungarees & Jumpsuits",
      "Skirts & shorts",
      "Tights & Leggings",
      "Jeans, Trousers & Capris",
      "Jacket, Sweater & Sweatshirts",
      "Innerwear & Thermals",
      "Nightwear & Loungewear",
      "Value Packs",
    ],
  },
  {
    name: "Footwear",
    list: [
      "Casual Shoes",
      "Flipflops",
      "Sports Shoes",
      "Flats",
      "Sandals",
      "Heels",
      "School Shoes",
      "Socks",
    ],
  },
  {
    name: "Toys_and_Games",
    list: [
      "Learning & Development",
      "Activity Toys",
      "Soft Toys",
      "Action Figure / Play set",
    ],
  },
  {
    name: "Infants",
    list: [
      "Bodysuits",
      "Rompers & Sleepsuits",
      "Clothing Sets",
      "Tshirts & Tops",
      "Dresses",
      "Bottom wear",
      "Winter Wear",
      "Innerwear & Sleepwear",
      "Infant Care",
    ],
  },
  {
    name: "Kids Accessories",
    list: [
      "Bags & Backpacks",
      "Watches",
      "Jewellery & Hair accessory",
      "Sunglasses",
      "Masks & Protective Gears",
      "Caps & Hats",
    ],
  },
  {
    name: "Brands",
    list: [
      "H&M",
      "Max Kids",
      "Pantaloons",
      "United Colors Of Benetton Kids",
      "YK",
      "U.S. Polo Assn. Kids",
      "Mothercare",
      "HRX",
    ],
  },
];
export const HOME_LIVING = [
  {
    name: "Bed Linen & Furnishing",
    list: [
      "Bed Runners",
      "Mattress Protectors",
      "Bedsheets",
      "Bedding Sets",
      "Blankets, Quilts & Dohars",
      "Pillows & Pillow Covers",
      "Bed Covers",
      "Diwan Sets",
      "Chair Pads & Covers",
      "Sofa Covers",
    ],
  },
  {
    name: "Flooring",
    list: ["Floor Runners", "Carpets", "Floor Mats & Dhurries", "Door Mats"],
  },
  {
    name: "Bath",
    list: [
      "Bath Towels",
      "Hand & Face Towels",
      "Beach Towels",
      "Towels Set",
      "Bath Rugs",
      "Bath Robes",
      "Bathroom Accessories",
      "Shower Curtains",
    ],
  },
  {
    name: "Lamps & Lighting",
    list: [
      "Floor Lamps",
      "Ceiling Lamps",
      "Table Lamps",
      "Wall Lamps",
      "Outdoor Lamps",
      "String Lights",
    ],
  },
  {
    name: "Home Décor",
    list: [
      "Plants & Planters",
      "Aromas & Candles",
      "Clocks",
      "Mirrors",
      "Wall Décor",
      "Festive Decor",
      "Pooja Essentials",
      "Wall Shelves",
      "Fountains",
      "Showpieces & Vases",
      "Ottoman",
    ],
  },
  {
    name: "Kitchen & Table",
    list: [
      "Table Runners",
      "Dinnerware & Serveware",
      "Cups and Mugs",
      "Bakeware & Cookware",
      "Kitchen Storage & Tools",
      "Bar & Drinkware",
      "Table Covers & Furnishings",
    ],
  },
  {
    name: "Storage",
    list: ["Bins", "Hangers", "Organisers", "Hooks & Holders", "Laundry Bags"],
  },
];

export const MEN = [
  {
    name: "Topwear",
    list: [
      "T-Shirts",
      "Casual Shirts",
      "Formal Shirts",
      "Sweatshirts",
      "Sweaters",
      "Jackets",
      "Blazers & Coats",
      "Suits",
      "Rain Jackets",
    ],
  },
  {
    name: "Indian & Festive Wear",
    list: ["Kurtas & Kurta Sets", "Sherwanis", "Nehru Jackets", "Dhotis"],
  },
  {
    name: "Bottomwear",
    list: [
      "Jeans",
      "Casual Trousers",
      "Formal Trousers",
      "Shorts",
      "Track Pants & Joggers",
    ],
  },
  {
    name: "Innerwear & Sleepwear",
    list: [
      "Briefs & Trunks",
      "Boxers",
      "Vests",
      "Sleepwear & Loungewear",
      "Thermals",
    ],
  },
  {
    name: "Footwear",
    list: [
      "Casual Shoes",
      "Sports Shoes",
      "Formal Shoes",
      "Sneakers",
      "Sandals & Floaters",
      "Flip Flops",
      "Socks",
    ],
  },
  {
    name: "Personal Care & Grooming",
    list: ["Trimmers", "Deodorants", "Perfumes & Body Mists"],
  },
  {
    name: "Accessories",
    list: [
      "Watches",
      "Sunglasses & Frames",
      "Wallets",
      "Belts",
      "Ties, Cufflinks & Pocket Squares",
      "Accessory Gift Sets",
      "Caps & Hats",
      "Mufflers, Scarves & Gloves",
      "Rings & Wristwear",
      "Helmets",
    ],
  },
  {
    name: "Sports & Active Wear",
    list: [
      "Sports Shoes",
      "Sports Sandals",
      "Active T-Shirts",
      "Track Pants & Shorts",
      "Tracksuits",
      "Jackets & Sweatshirts",
      "Sports Accessories",
      "Swimwear",
    ],
  },
  {
    name: "Gadgets",
    list: [
      "Smart Wearables",
      "Fitness Gadgets",
      "Headphones",
      "Speakers",
      "Phone Cases",
    ],
  },
  { name: "Bags & Luggage", list: ["Bags & Backpacks", "Luggage & Trolleys"] },
];
export const WOMEN = [
  {
    name: "Indian_and_Fusion_Wear",
    list: [
      "Kurtas & Suits",
      "Kurtis, Tunics & Tops",
      "Sarees",
      "Ethnic Wear",
      "Leggings, Salwars & Churidars",
      "Skirts & Palazzos",
      "Dress Materials",
      "Lehenga Cholis",
      "Dupattas & Shawls",
      "Jackets",
    ],
  },

  {
    name: "Western_Wear",
    list: [
      "Dresses",
      "Tops",
      "Tshirts",
      "Jeans",
      "Trousers & Capris",
      "Shorts & Skirts",
      "Co-ords",
      "Playsuits",
      "Jumpsuits",
      "Shrugs",
      "Sweaters & Sweatshirts",
      "Jackets & Coats",
      "Blazers & Waistcoats",
    ],
  },
  {
    name: "Footwear",
    list: [
      "Flats",
      "Casual Shoes",
      "Heels",
      "Boots",
      "Sports Shoes & Floaters",
    ],
  },
  {
    name: "Sports_and_Active_Wear",
    list: ["Clothing", "Footwear", "Sports Accessories", "Sports Equipment"],
  },
  {
    name: "Lingerie_Sleepwear",
    list: [
      "Bra",
      "Briefs",
      "Shapewear",
      "Sleepwear & Loungewear",
      "Swimwear",
      "Camisoles & Thermals",
    ],
  },
  {
    name: "Beauty_and_Personal_Care",
    list: ["Makeup", "Skincare", "Premium Beauty", "Lipsticks", "Fragrances"],
  },
  {
    name: "Gadgets",
    list: ["Smart Wearables", "Fitness Gadgets", "Headphones", "Speakers"],
  },
  {
    name: "Jewellery",
    list: ["Fashion Jewellery", "Fine Jewellery", "Earrings"],
  },
];

